# Generated by Django 4.2.7 on 2025-11-06 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('skill_approved', 'Skill Approved'), ('skill_rejected', 'Skill Rejected'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_warned', 'User Warned'), ('report_reviewed', 'Report Reviewed'), ('report_resolved', 'Report Resolved'), ('report_dismissed', 'Report Dismissed'), ('task_deleted', 'Task Deleted'), ('payment_refunded', 'Payment Refunded'), ('system_config', 'System Configuration Changed'), ('other', 'Other Action')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the action taken')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.report')),
                ('target_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentskill')),
                ('target_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_adminl_created_b62f8b_idx'), models.Index(fields=['admin', '-created_at'], name='core_adminl_admin_i_5b404a_idx'), models.Index(fields=['action', '-created_at'], name='core_adminl_action_4b811f_idx')],
            },
        ),
    ]
