# Generated by Django 4.2.7 on 2025-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chat_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
