# Generated by Django 4.2.7 on 2025-11-11 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_chat_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(help_text='Why are you a good fit for this task?')),
                ('proposed_timeline', models.CharField(blank=True, help_text='When can you complete this?', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('doer_rating_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('doer_completed_tasks_snapshot', models.IntegerField(default=0)),
                ('doer_is_newbie', models.BooleanField(default=False, help_text='True if doer has < 3 completed tasks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_applications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'status'], name='core_taskap_task_id_a19433_idx'), models.Index(fields=['doer', 'status'], name='core_taskap_doer_id_1101c4_idx')],
                'unique_together': {('task', 'doer')},
            },
        ),
    ]
