# Generated by Django 4.2.7 on 2025-11-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taskapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned'), ('accepted', 'Accepted by Agent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assignment_method', models.CharField(choices=[('automatic', 'Automatic Assignment'), ('manual', 'Manual Assignment'), ('application', 'Agent Application')], default='automatic', max_length=20)),
                ('skill_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('workload_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_notes', models.TextField(blank=True, help_text='Reason for assignment')),
                ('reassignment_reason', models.TextField(blank=True, help_text='Reason for reassignment')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('task', 'payer', 'receiver')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='core_paymen_status_fcd0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', '-created_at'], name='core_paymen_payer_i_fbeba8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receiver', '-created_at'], name='core_paymen_receive_e59d30_idx'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.task'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'status'], name='core_taskas_task_id_886fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['agent', 'status'], name='core_taskas_agent_i_60d7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['-assigned_at'], name='core_taskas_assigne_c0d2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status'], name='core_taskas_status_6e509d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'agent')},
        ),
    ]
