# Generated by Django 4.2.7 on 2025-11-27 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taskassignment_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Wallet',
                'verbose_name_plural': 'System Wallet',
            },
        ),
    ]
