# Generated by Django 4.2.7 on 2025-11-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='first_application_time',
            field=models.DateTimeField(blank=True, help_text='Time when first application was received', null=True),
        ),
    ]
