# Generated by Django 4.2.7 on 2025-11-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_database_indexes'),
        ('core', '0007_taskapplication_first_application_time'),
    ]

    operations = [
    ]
