# Generated by Django 4.2.7 on 2025-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20251128_1336'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_task_id_516578_idx',
            old_name='message_task_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_sender__064541_idx',
            old_name='message_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_created_a655d0_idx',
            old_name='message_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_task_id_c2314b_idx',
            old_name='message_task_created_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_status_e18e62_idx',
            old_name='task_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_poster__514bde_idx',
            old_name='task_poster_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_doer_id_76c7da_idx',
            old_name='task_doer_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_created_9e4493_idx',
            old_name='task_created_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_status_b16367_idx',
            old_name='task_status_created_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymongo_source_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
