# Generated by Django 4.2.7 on 2025-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_message_task_idx_core_messag_task_id_516578_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
