# Generated by Django 4.2.7 on 2025-12-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='pending', max_length=25),
        ),
    ]
