# Generated by Django 4.2.7 on 2026-01-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcommission',
            name='commission_type',
            field=models.CharField(choices=[('system_fee', 'System Fee'), ('chat_unlock', 'Chat Unlock Fee')], default='system_fee', max_length=20),
        ),
    ]
