# Generated by Django 4.2.7 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemcommission_commission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcommission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
