# Generated by Django 4.2.7 on 2026-01-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_systemcommission_description'),
    ]

    operations = [
        # Add fields to SystemCommission model
        migrations.AddField(
            model_name='systemcommission',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.00, max_digits=5, help_text='Commission percentage (default 10%)'),
        ),
        migrations.AddField(
            model_name='systemcommission',
            name='task_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, help_text='Original task amount'),
        ),
        migrations.AddField(
            model_name='systemcommission',
            name='doer_receives',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, help_text='Amount doer will receive after commission'),
        ),
        migrations.AddField(
            model_name='systemcommission',
            name='deducted_at',
            field=models.DateTimeField(null=True, blank=True, help_text='When commission was deducted from task amount'),
        ),
        
        # Add fields to Task model
        migrations.AddField(
            model_name='task',
            name='commission_deducted',
            field=models.BooleanField(default=False, help_text='Whether commission has been deducted'),
        ),
        migrations.AddField(
            model_name='task',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, help_text='Commission amount (10% of task price)'),
        ),
        migrations.AddField(
            model_name='task',
            name='doer_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, help_text='Amount to pay doer (price - commission)'),
        ),
    ]
