# Generated by Django 4.2.7 on 2026-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_commission_percentage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='campus_location',
            field=models.CharField(blank=True, choices=[('agriculture', 'College of Agriculture'), ('arts_sciences', 'College of Arts and Sciences'), ('education', 'College of Teachers Education'), ('engineering', 'College of Engineering'), ('business', 'College of Business Administration'), ('computing', 'College of Computing and Information Sciences'), ('other', 'Other / Off-Campus')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='campus_location',
            field=models.CharField(blank=True, choices=[('agriculture', 'College of Agriculture'), ('arts_sciences', 'College of Arts and Sciences'), ('education', 'College of Teachers Education'), ('engineering', 'College of Engineering'), ('business', 'College of Business Administration'), ('computing', 'College of Computing and Information Sciences'), ('other', 'Other / Off-Campus')], help_text="Student's home base", max_length=50),
        ),
    ]
