# Generated by Django 4.2.7 on 2026-01-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='msg_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_task_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_task_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_poster_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_doer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_category_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskapplication',
            name='app_task_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskapplication',
            name='app_doer_status_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('payment_received', 'Payment Received'), ('rating_received', 'Rating Received'), ('skill_verified', 'Skill Verified'), ('report_filed', 'Report Filed'), ('system_message', 'System Message'), ('deadline_reminder', 'Deadline Reminder'), ('task_overdue', 'Task Overdue'), ('task_expired', 'Task Expired')], max_length=20),
        ),
    ]
