# Generated by Django 4.2.7 on 2026-01-31 08:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_message_msg_read_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_assign_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic assignment based on matching algorithm'),
        ),
        migrations.AddField(
            model_name='task',
            name='flexible_timing',
            field=models.BooleanField(default=False, help_text='Allow flexible scheduling outside preferred window'),
        ),
        migrations.AddField(
            model_name='task',
            name='preferred_delivery_time',
            field=models.TimeField(blank=True, help_text='Specific preferred time of day', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='preferred_doer',
            field=models.ForeignKey(blank=True, help_text='Preferred doer for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.IntegerField(default=3, help_text='Priority level (1=Low, 3=Normal, 5=Urgent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='task',
            name='time_window_end',
            field=models.DateTimeField(blank=True, help_text='Preferred end time for task execution', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_window_start',
            field=models.DateTimeField(blank=True, help_text='Preferred start time for task execution', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blacklisted_doers',
            field=models.ManyToManyField(blank=True, help_text='Doers blocked by this user', related_name='blacklisted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Notification settings and preferences'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.JSONField(blank=True, default=list, help_text='Preferred task categories for matching'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_communication',
            field=models.CharField(choices=[('chat', 'Chat'), ('email', 'Email'), ('phone', 'Phone')], default='chat', help_text='Preferred communication method', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_doer_types',
            field=models.JSONField(blank=True, default=list, help_text="Preferred doer types: ['microtasker', 'skilled', 'both']"),
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time')),
                ('scheduled_end', models.DateTimeField(help_text='Scheduled end time')),
                ('buffer_time', models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Buffer time before/after task')),
                ('auto_reschedule', models.BooleanField(default=False, help_text='Automatically reschedule if conflicts arise')),
                ('priority_level', models.IntegerField(default=3, help_text='Scheduling priority (1=Low, 5=Urgent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_confirmed', models.BooleanField(default=False, help_text='Schedule confirmed by doer')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Scheduling notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.task')),
            ],
            options={
                'verbose_name': 'Task Schedule',
                'verbose_name_plural': 'Task Schedules',
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['scheduled_start'], name='core_tasksc_schedul_3a406b_idx'), models.Index(fields=['task', 'is_confirmed'], name='core_tasksc_task_id_4af6b1_idx'), models.Index(fields=['priority_level', '-scheduled_start'], name='core_tasksc_priorit_6e4dfb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Availability start time')),
                ('end_time', models.TimeField(help_text='Availability end time')),
                ('is_available', models.BooleanField(default=True, help_text='Currently available')),
                ('recurring', models.BooleanField(default=True, help_text='Repeats weekly')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doer Availability',
                'verbose_name_plural': 'Doer Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['doer', 'day_of_week'], name='core_doerav_doer_id_61430f_idx'), models.Index(fields=['doer', 'is_available'], name='core_doerav_doer_id_c94c7e_idx')],
                'unique_together': {('doer', 'day_of_week', 'start_time')},
            },
        ),
    ]
