# Generated by Django 4.2.7 on 2026-02-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_task_auto_assign_enabled_task_flexible_timing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doeravailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doeravailability',
            name='doer',
        ),
        migrations.RemoveField(
            model_name='taskschedule',
            name='task',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blacklisted_doers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_communication',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_doer_types',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('payment_received', 'Payment Received'), ('rating_received', 'Rating Received'), ('skill_verified', 'Skill Verified'), ('report_filed', 'Report Filed'), ('system_message', 'System Message')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority_level', '-created_at'], name='core_task_priorit_e8d11e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['time_window_start', 'time_window_end'], name='core_task_time_wi_d146f7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['preferred_doer', 'status'], name='core_task_preferr_05365e_idx'),
        ),
        migrations.DeleteModel(
            name='DoerAvailability',
        ),
        migrations.DeleteModel(
            name='TaskSchedule',
        ),
    ]
