# Generated by Django 4.2.7 on 2026-02-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_doeravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File')], max_length=20, null=True),
        ),
    ]
