# Generated by Django 4.2.7 on 2026-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=100)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
